### ISSUE TITLE
怎么让导航条距离底部有一点的距离

### ISSUE THREAD

**Issue by PangHaHa12138** [shallcheek/CaterpillarIndicator#1]
![image](https://user-images.githubusercontent.com/28802276/29014978-788fe0fc-7b7e-11e7-93fa-24f5a515cfc9.png)
nin您好，不知道怎么可以设置导航条距离底部有一些距离2dp-3dp 现在导航条是紧紧贴在下面的

**Comment by shallcheek** [comment]
compile 'com.chaek.android:caterpillarindicator:1.2.0'

使用最新版本 添加slide_padding_bottom属性可以实现设计图对应的效果
